

services:
  epr:
    image: docker.elastic.co/package-registry/distribution:${STACK_VERSION}
    container_name: epr
    restart: always
    ports:
      - ${EPR_PORT}:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f -L http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 120

  ear:
    image: elastic-artifact-registry:${STACK_VERSION}
    build:
      context: elastic_artifact_registry_container
      dockerfile: Dockerfile
      args:
        - ELASTIC_VERSION=${STACK_VERSION}
    container_name: ear
    restart: always
    ports:
      - ${EAR_PORT}:9080
    healthcheck:
      test: ["CMD-SHELL", "curl -f -L http://localhost:9080/"]
      interval: 10s
      timeout: 10s
      retries: 120   

  kibana:
    depends_on:
      epr:
        condition: service_healthy
    environment:
      - XPACK_FLEET_REGISTRYURL=http://epr:8080


  fleet-server:
    volumes:
      - ./fleet-startup.sh:/usr/share/elastic-agent/fleet-startup.sh


