services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_GUI_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_GUI_PORT}"
    volumes:
      - minio-data:/data

volumes:
  minio-data: