# syntax=docker/dockerfile:1

FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY main.py main.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info", "--workers", "1"]