# # Elasticsearch 
# # elasticsearch:
# #   host: "https://${DOCKER_HOST_IP}:${ES_PORT}"  
# #   username: "elastic"                           
# #   password: "${ELASTIC_PASSWORD}"               

# #   ssl:
# #     certificateAuthorities: ["/certs/ca/ca.crt"] 
# #     certificate: "/certs/elastic-certificates.crt" 
# #     key: "/certs/elastic-certificates.key"         
# #     keyPassphrase: ""                              
# #     verificationMode: "full"                       
# # General settings
# # host: localhost       
# # #port: ${CUSTOM_MAPS_SERVICE_PORT}  
# # port: 8085               
# basePath: "/maps"                  
# ui: true                           

# # Logging settings
# logging:
#   level: "info"                    

# path:
#   planet: "/usr/src/app/data/planet.mbtiles" 


# Specifies the address to which the Elastic Maps Server server will bind. IP addresses and
# host names are both valid values. The default is the `hostname` of the Docker container.
# host: elastic-maps-server

# This setting specifies the port the server runs on inside the Docker container. The default
# is 8080. Typically you'll want to expose this port from Docker.
# port: 8080

# Required settings for the URL and basic authentication parameters for your Elasticsearch
# cluster for license verification.
# elasticsearch.host: 'http://elasticsearch:9200'
# elasticsearch.username: 'ems'
# elasticsearch.password: 'changeme'

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files are used to verify the identity of Elastic Maps Server to Elasticsearch and
# are required when xpack.security.http.ssl.client_authentication in Elasticsearch is set
# to required.
# elasticsearch.ssl.certificate: /etc/ssl/certs/elasticsearch.crt
# elasticsearch.ssl.key: /etc/ssl/certs/elasticsearch.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
# elasticsearch.ssl.certificateAuthorities: [ /etc/ssl/certs/CA.pem ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
# elasticsearch.ssl.verificationMode: full

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Elastic Maps Server server to
# the browser.
# ssl.enabled: false
# ssl.certificate: /etc/ssl/certs/ems.crt
# ssl.key: /etc/ssl/certs/ems.key

# Location of planet tiles database
path.planet: /usr/src/app/data/planet.mbtiles

# Logging level for Elastic Maps Server logs
logging.level: info

# Optional: Should the status and layer preview be enabled? (default: true)
# ui: true