elastic:
  apm:
    active: true
    # serverUrl: "http://${DOCKER_HOST_IP}:${APMSERVER_PORT}"
    serverUrl: "http://fleet-server:8200"
    secretToken: ${ELASTIC_APM_SECRET_TOKEN}
    environment: Elastic_Stack
server.host: "0.0.0.0"
telemetry.enabled: "true"

xpack.fleet.fleetServerHosts:
  - id: external_fleet_server
    name: External Fleet Server URL
    host_urls: ["https://${DOCKER_HOST_IP}:${FLEET_PORT}"]
    is_default: true
  - id: internal_fleet_server
    name: Internal Docker Fleet Server URL
    host_urls: ["https://fleet-server:8220"]
    # is_internal: true

xpack.fleet.outputs:
  - id: external_elasticsearch_output
    name: External Elasticsearch Output
    type: elasticsearch
    hosts: ["https://${DOCKER_HOST_IP}:${ES_PORT}"]
    is_default: true
    is_default_monitoring: true
    config:
      ssl.certificate_authorities: ["/certs/ca/ca.crt"]
  # Uncomment to enable multiple outputs - requires Platinum or above license
  # - id: interal_docker_elasticsearch_output
  #   name: Interal Docker Elasticsearch Output
  #   type: elasticsearch
  #   hosts: ["https://es01:9200"]
  #   config:
  #     ssl.certificate_authorities: ["/certs/ca/ca.crt"]

xpack.fleet.packages:
  - name: fleet_server
    version: latest
  - name: system
    version: latest
  - name: elastic_agent
    version: latest
  - name: apm
    version: latest
  - name: docker
    version: latest
  # - name: cef
  #   version: latest

xpack.fleet.agentPolicies:
  - name: Fleet-Server-Policy
    id: fleet-server-policy
    namespace: default
    fleet_server_host_id: internal_fleet_server
    # Uncomment to enable multiple outputs - requires Platinum or above license
    # data_output_id: interal_docker_elasticsearch_output
    # monitoring_output_id: interal_docker_elasticsearch_output
    monitoring_enabled: 
      - logs
      - metrics
    package_policies:
      - name: fleet_server-1
        package:
          name: fleet_server
      - name: system-1
        package:
          name: system
      - name: elastic_agent-1
        package:
          name: elastic_agent
      - name: docker-1
        package:
          name: docker
      - name: apm-1
        package:
          name: apm
        inputs:
          - type: apm
            enabled: true
            vars:
              - name: host
                value: 0.0.0.0:8200
              - name: secret_token
                value: ${ELASTIC_APM_SECRET_TOKEN}
  - name: Docker-Container-Policy
    id: docker-container-policy
    namespace: default
    fleet_server_host_id: internal_fleet_server
    # Uncomment to enable multiple outputs - requires Platinum or above license
    # data_output_id: interal_docker_elasticsearch_output
    # monitoring_output_id: interal_docker_elasticsearch_output
    monitoring_enabled: 
      - logs
      - metrics
    package_policies:
      - name: system-docker_agent
        package:
          name: system





      