input {
  file {
    #https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html
    #default is TAIL which assumes more data will come into the file.
    #change to mode => "read" if the file is a compelte file.  by default, the file will be removed once reading is complete -- backup your files if you need them.
    mode => "tail"
    path => "/usr/share/logstash/ingest_data/*"
  }
}

filter {
    csv {
    separator => ","
    autodetect_column_names => true
  }
}
# https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html
output {
  kafka {
    bootstrap_servers => "kafka01:9092"
    topic_id => "elk-docker"
  }
}
